### ISSUE TITLE
[Bug] - lvm: Timed out waiting for device after reboot

### ISSUE THREAD

**Issue by nicolasnoel** [amazonlinux/amazon-linux-2023#339]
**Describe the bug**
When mounting lvm filesystem, and register the instance as an AMI, new instance launched from that AMI doen't start and fall back to emergency mode

**To Reproduce**
1. Start an instance from AmazonLinux 2023
2. install lvm : `dnf install lvm2`
3. add an ebs volume, create pv, vg and lv
4. mount the lv
5. register an AMI from the instance
6. launch a new instance, it never boots and display this message in the serial console [(serial console.log)](https://github.com/amazonlinux/amazon-linux-2023/files/11404407/serial.console.log):
```
[ [0;1;31m TIME [0m] Timed out waiting for device - /dev/disk/by-label/var_log.
...
You are in emergency mode. After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or "exit"
to boot into default mode.

```

**Expected behavior**
the logical volume should get mounted

**Desktop (please complete the following information):**
 - OS: amazon linux 2023 x86_64 and arm64
 - ami id: `ami-03aefa83246f44ef2` (x86_64) & `ami-0452d2386670510e8` (arm64)

**Additional context**
The AMI construction id made with hashicorp packer & ansible, the exat same build works with Amazon Linux 2.
I also tried mount option `x-systemd.device-timeout=300`in /etc/fstab, but doesn't solce the issue

**Comment by ozbenh** [comment]
Did you add it to `/etc/fstab` at all ? DId anything to `lvm.conf` ? or the simple existence of the lvm volume is sufficient to cause this ?

**Comment by nicolasnoel** [comment]
Yes, indeed, at step 4 'mount the lv', as this is done with ansible, the ansible module adds the mount to `/etc/fstab`
Did nothing on `lvm.conf`

**Comment by stewartsmith** [comment]
If you have set it up to mount from the initramfs, we don't by default include lvm in the initramfs, and you'll need to modify the dracut config and regenerate initramfs.

**Comment by nicolasnoel** [comment]
Ok thanks, I'll try that.

Is that a difference with amazon linux 2 ? 
How was lvm included in al2 ?

**Comment by nicolasnoel** [comment]
Great ! Thanks a lot @tcicone01 !!


To make it work, I had to install package `device-mapper-multipath`


and add `create: true` to al3.conf config:
```
- name: Update /etc/dracut.conf.d/al3.conf
  blockinfile:
    path: /etc/dracut.conf.d/al3.conf
    create: true
    block: |
      add_dracutmodules+=" dbus dbus-broker dm multipath lvm udev-rules rootfs-block systemd usrmount "
      lvmconf="yes"
  when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2023'
```
