### ISSUE TITLE
[Bug] - Install of git lfs fails in Codebuild

### ISSUE THREAD

**Issue by hizzuu** [amazonlinux/amazon-linux-2023#385]
**Describe the bug**
 Install of git lfs fails in Codebuild
```yml
phases:
  install:
    commands:
      - wget https://github.com/git-lfs/git-lfs/releases/download/v3.1.2/git-lfs-linux-arm64-v3.1.2.tar.gz
      - tar -xvf git-lfs-linux-arm64-v3.1.2.tar.gz
      - bash ./install.sh
      - git lfs install
```

```
[Container] 2023/06/29 03:26:23 Running command bash ./install.sh
--
193 | /usr/local/bin/git-lfs: /usr/local/bin/git-lfs: cannot execute binary file
194 |  
195 | [Container] 2023/06/29 03:26:23 Command did not exit successfully bash ./install.sh exit status 126
196 | [Container] 2023/06/29 03:26:23 Phase complete: INSTALL State: FAILED
```

**To Reproduce**

image
- aws/codebuild/amazonlinux2-x86_64-standard:5.0

type
- Linux

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
